spring:
  application:
    ####注册中心应用名称
    name:  config-client
  cloud:
    config:
    ####读取后缀
      profile: dev
      ####读取config-server注册地址
      discovery:
       #表示使用服务发现组件中提供的Config Server，默认是false
        service-id: config-server
        enabled: true #开启通过服务发现组件访问Config Server的功能
#####    eureka服务注册地址
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
           defaultZone: http://localhost:8888/eureka
server:
  port: 8881
###开启bus刷新
#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh

