eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8764
spring:
  application:
    name: service-order
feign:
   hystrix:
     enabled: true
###超时时间
hystrix:
   command:
     default:
       execution:
        isolation:
         thread:
          timeoutInMilliseconds: 4000